config/routes.rb
Rails.application.routes.draw do

  get 'posts' => 'posts#new'

  post 'posts' => 'posts#create'

  get 'posts' => 'posts#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'pages#home'
  get 'signup' => 'users#new'
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save {self.email= email.downcase}
	validates :name, presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255},
	format: { with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true

	 # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
  	self.remember_token=User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end
# Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  #forgets a user.
  def forget
  	update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def signup
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create]

	def new
	end

	def create
		
	end

	def index
	end

#filters.
	def logged_in_user
		unless logged_in?
			flash[:danger]= "you have to be logged in."
			redirect_to login_url
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user=User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		remember user
  		redirect_to user
  	else
  		flash.now[:danger]='Invalid email/password'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user=User.find(params[:id])
	end

	def new
		@user=User.new
	end

	def create
		@user= User.new(user_params)
		if @user.save
			flash[:sucess] = "Let the gossip begin"
			log_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#logs in the given user
	def log_in(user)
		session[:user_id]= user.id
	end
	#returns the current logged in user(if one exists)
	def current_user
	    if (user_id = session[:user_id])
	      @current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.signed[:user_id])
	      user = User.find_by(id: user_id)
		      if user && user.authenticated?(cookies[:remember_token])
		        log_in user
		        @current_user = user
		    end
	    end
  	end

  	#returns true if the user is logged in, or false if not.
  	def logged_in?
  		!current_user.nil?
  	end
  	#logs the user out
  	def log_out
  		forget(current_user)
  		session.delete(:user_id)
  		@current_user=nil
  	end
  	#remembers a user in a persistent session
  	def remember(user)
  		user.remember
  		cookies.permanent.signed[:user_id]= user.id
  		cookies.permanent[:remember_token]= user.remember_token
  	end
  	#forgets a persistent session
  	def forget(user)
  		user.forget
  		cookies.delete(:user_id)
  		cookies.delete(:remember_token)
  	end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Clubhouse", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Users" , '#' %></li>
            <li><%= link_to "Write a new Post" ,posts_path %></li>
            <li><%= link_to "My Posts", posts_path %></li>
            <li class= "dropdown">
              <a href="#" class= "dropdown-toggle" data-toggle="dropdown">
              Account<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                  <li><%=link_to "Profile",current_user %></li>
                  <li><%=link_to "Settings", '#' %></li>
                  <li class= "divider"></li>
                  <li>
                    <%=link_to "log out", logout_path, method: "delete" %>
                  </li>
              </ul>              
            </li>
          <% else %>
            <li><%=link_to "Log in", login_path %> </li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Clubhouse</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>The Clubhouse</h1>
		<p>Welcome to the Clubhouse. Here you can share stories about people, and be completely anonymous.</p>

		<%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Write a new post!</h1>
<div class= "posts">
<%= form_for(:posts) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :post %>
	<%= f.text_field :post %>

	<%= f.submit "Submit your story" %>

	
<% end %>
	
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New Users</h1>
<h2 id="h2">Aye, fresh meat!</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
	    <%= render 'shared/error_messages' %>
	      <%= f.label :name %>
	      <%= f.text_field :name, class: 'form-control' %>

	      <%= f.label :email %>
	      <%= f.email_field :email, class: 'form-control' %>

	      <%= f.label :password %>
	      <%= f.password_field :password, class: 'form-control' %>

	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, class: 'form-control' %>

	      <%= f.submit "Create my account", class: "btn btn-primary" %>
	    <% end %>
	  </div>
	</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>